package corp.tbm.cleanarchitecturemapper.foundation.codegen.universal.exceptions.references

import corp.tbm.cleanarchitecturemapper.foundation.codegen.universal.exceptions.CleanWizardFieldAlreadyMarkedWithEnumException

typealias PropertyAlreadyMarkedWithEnumException = CleanWizardFieldAlreadyMarkedWithEnumException