package corp.tbm.cleanwizard.foundation.codegen.exceptions.references

import corp.tbm.cleanwizard.foundation.codegen.exceptions.CleanWizardFieldAlreadyMarkedWithEnumException

typealias PropertyAlreadyMarkedWithEnumException = CleanWizardFieldAlreadyMarkedWithEnumException